services:
  - type: web
    name: ocrmind
    runtime: python
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.9

    # Temporarily added "&& ls -laR" to list all deployed files
    buildCommand: "pip install -r 3_WebApp/requirements.txt && ls -laR"

    startCommand: "gunicorn --workers 3 --chdir 3_WebApp main:app"