services:
  - type: web
    name: ocrmind
    runtime: python
    buildCommand: "cd 3_WebApp && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "cd 3_WebApp && gunicorn main:app"
    region: oregon
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
