services:
  - type: web
    name: ocrmind
    runtime: python
    buildCommand: "cd 3_WebApp && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    region: oregon
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    buildFilter:
      paths:
        - 3_WebApp/**
    rootDir: 3_WebApp
